config/routes.rb
Athirdplace::Application.routes.draw do 
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations", sessions: "sessions"}
  devise_scope :user do
    match "/users/sign_out" => "sessions#destroy"
  end  
  resources :users, only: [:index, :show]
  resources :communities, only: [:index]
  resources :posts
  resources :links
  resources :events
  match 'posts/new/preview', to: 'posts#preview', as: "preview_post"
  match 'posts/new/show_tags', to: 'posts#show_tags', as: "show_tags"
  resources :comments, only: [:new, :create, :show]
  resources :conversations, only: [:index, :show]
  resources :messages, only: [:new, :create]
  resources :subscriptions, only: [:index, :new, :create]
  match "", to: "users#index", constraints: lambda { |r| r.subdomain.present? && r.subdomain != "www" }
  root to: "users#home"
  

end

app/models/conversation.rb
class Conversation
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  
  has_many :messages
  has_and_belongs_to_many :users
  
  def partner(user)
    users.ne(id: user.id).first
  end
  
  # Check for unread messages
  def has_unread_by(user)
    Message.any_in(conversation_id: id).ne(read_by: user.id).present?
  end  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    # Inbox
    @conversations = current_user.conversations.desc(:updated_at)
    
    # Show first conversation + messages
    @conversation = params[:id] ? Conversation.find_by(id: params[:id]) : @conversations.first
    if @conversation
      @messages = @conversation.messages.asc(:created_at)
      @user = @conversation.partner(current_user)
      
      # Update read_by status
      if @messages.present?
        @conversation.messages.unread_by(current_user).each do |message|
          message.add_to_set(:read_by, current_user.id) 
        end
      end
      
    end
  end
  
  def show
    @conversation = Conversation.find(params[:id])
    @messages = @conversation.messages.asc(:created_at)
    @user = @conversation.partner(current_user)
    # Update read status
    @conversation.messages.last.add_to_set(:read_by, current_user.id) if @messages.present?    
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.haml
.conversation
	= link_to conversation_path(conversation), remote: true do
		.conversation_image
			= image_tag conversation.partner(current_user).image
		.conversation_user{:id => "#{conversation.id}", :class => conversation == @conversation ? "current" : nil}
			= conversation.partner(current_user).first_name
			- if conversation.has_unread_by(current_user)
				%i.icon-envelope
		%div{style:"clear:both"}

app/views/conversations/_empty.html.haml
#conversation-empty
	%i.icon-caret-right
	No conversations yet -
	= link_to "introduce yourself to someone interesting", users_path

app/views/conversations/_show.html.haml
#conversation-user.hidden-phone
	= render user
#conversation-messages
	#conversation-dialog
		= render messages
	= form_for Message.new, remote: true do |f|
		= f.text_area :body
		= f.hidden_field :conversation_id, { value: conversation.id }
		= f.submit "Send", :id => "submit_message", :class => "btn btn-primary"
%div{style:"clear:right"}

app/views/conversations/index.html.haml
- content_for :javascript do
	= javascript_include_tag 'autosize.min', 'timeago', 'conversations'
.row
	.span4
		#inbox
			.filters_title
				%span Conversations
			= render @conversations
	.span8
		#conversation
			- if @conversation
				= render partial: 'conversations/show', locals: { conversation: @conversation, messages: @messages, user: @user }
			- else
				= render 'conversations/empty'

app/views/conversations/show.js.erb
$('#conversation').html('<%= j render partial: "conversations/show", locals: { conversation: @conversation, messages: @messages, user: @user } %>');
$('abbr.timeago').timeago();
$('#message_body').autosize();
$('.current').removeClass('current');
$('#<%= @conversation.id %>').addClass('current');
$('#<%= @conversation.id %> i').remove();