config/routes.rb
Athirdplace::Application.routes.draw do 
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations", sessions: "sessions"}
  devise_scope :user do
    match "/users/sign_out" => "sessions#destroy"
  end  
  resources :users, only: [:index, :show]
  resources :communities, only: [:index]
  resources :posts
  resources :links
  resources :events
  match 'posts/new/preview', to: 'posts#preview', as: "preview_post"
  match 'posts/new/show_tags', to: 'posts#show_tags', as: "show_tags"
  resources :comments, only: [:new, :create, :show]
  resources :conversations, only: [:index, :show]
  resources :messages, only: [:new, :create]
  resources :subscriptions, only: [:index, :new, :create]
  match "", to: "users#index", constraints: lambda { |r| r.subdomain.present? && r.subdomain != "www" }
  root to: "users#home"
  

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include Geocoder::Model::Mongoid
  include ActionView::Helpers::TextHelper # Pluralize  
  # include Mongoid::Versioning
  
  has_and_belongs_to_many :communities
  has_and_belongs_to_many :conversations
  has_many :posts
  has_many :messages
  has_one :subscription
  
  attr_accessible :email, :provider, :uid, :oauth_token, :name, :first_name, :last_name, :image, :normal_image, 
                  :large_image, :facebook_url, :show_facebook_url, :twitter_name, :blog_url, :bio, :message_ids, 
                  :friend_ids, :coordinates, :community_ids, :gender_ids, :standing_ids, :degree_ids, :field_ids, 
                  :school_ids, :city_ids, :state_ids, :country_ids, :profession_ids, :company_ids, :relationship_ids, 
                  :orientation_ids, :religion_ids, :ethnicity_ids, :password, :password_confirmation, :encrypted_password
  
  validates :blog_url, allow_blank: true, url: true
  
  after_update :add_geo_from_user_city
  
  def add_geo_from_user_city
    if city_ids.present?
      # Add state or country
      if Community.find_by(id: city_ids.first).parent.present?
        self.communities << Community.find_by(id: city_ids.first).parent
      end
      
      # Add country if state
      if Community.find_by(id: city_ids.first).parent.parent.present?
        self.communities << Community.find_by(id: city_ids.first).parent.parent
      end
      
      # Add coordinates
      if Community.find_by(id: city_ids.first).coordinates.present? 
        self.coordinates = Community.find_by(id: city_ids.first).coordinates
      end
    end
  end
    
  %W[ gender standing field school city ].each do |community_type|
    validates community_type.to_sym, :presence => { :message => "is blank" }, :on => :update
  end
                   
  # Include default devise modules. Others available are: :token_authenticatable, :confirmable, :lockable, and :timeoutable
  # devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable, :validatable, :omniauthable, :trackable
  
  field :email, type: String
  field :encrypted_password, type: String
  field :provider, type: String
  field :uid, type: String
  field :oauth_token, type: String
  field :name, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :image, type: String
  field :normal_image, type: String
  field :large_image, type: String
  field :facebook_url, type: String
  field :show_facebook_url, type: Boolean
  field :twitter_name, type: String
  field :blog_url, type: String
  field :bio, type: String
  field :gender, type: String
  field :friend_ids, type: Array
  field :coordinates, type: Array
  
  index({ coordinates: "2d" }, { min: -200, max: 200 })  
  ## Database authenticatable
  # field :email,              :type => String, :null => false, :default => ""
  # field :encrypted_password, :type => String, :null => false, :default => ""

  ## Recoverable
  # field :reset_password_token,   :type => String
  # field :reset_password_sent_at, :type => Time

  ## Rememberable
  # field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  # Create custom methods
  %W[ gender standing degree field school city state country profession company relationship orientation ethnicity religion ].each do |community_type|
    define_method "#{community_type}" do
      array = self.communities.filtered_by(community_type)
      array.length == 1 ? array.first : array
    end
    define_method "#{community_type}_ids" do
      self.communities.filtered_by(community_type).map(&:id)
    end
    define_method "#{community_type}_ids=" do |val| 
      self.communities.clear if community_type == "gender"
      
      if community_type == "school" # Schools hack
        val.split(",").each do |school_id|
          self.communities << Community.find_by(id: school_id) if school_id != "[]" # Schools hack
        end
      
      elsif community_type == "profession" || community_type == "company"# Professions hack
        if val.present?
          if val.split(",").length == 1
            community = Community.where(id: val)
            new_community = Community.where(name: val, community_type: community_type)
            if community.present?
              self.communities << community.first
            elsif new_community.present?
              self.communities << new_community.first
            else
              self.communities << Community.create!(name: val, subdomain: val.to_s.delete(" ").delete("-").parameterize, display_name: "#{val} Network", display_name: "#{val} Network", nickname: val, community_type: community_type.titleize)             
            end
          else
            first_val = val.split(",").first
            community = Community.where(id: first_val)
            new_community = Community.where(name: first_val, community_type: community_type)
            if community.present?
              self.communities << community.first
            elsif new_community.present?
              self.communities << new_community.first
            else
              self.communities << Community.create!(name: first_val, subdomain: first_val.to_s.delete(" ").delete("-").parameterize, display_name: "#{first_val} Network", display_name: "#{first_val} Network", nickname: first_val, community_type: community_type.titleize)             
            end
          end
        end
      else  
        if val.class == Array
          val.each do |id|
            self.communities << Community.find_by(id: id) if id.present?
          end
        else
          self.communities << Community.find_by(id: val) if val.present? && val != "[]" # Cities hack
        end
      end
    end
  end
  
  # Omniauth authentication
  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.oauth_token = auth.credentials.token
      user.email = auth.info.email
      user.name = auth.info.name
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.image = auth.info.image
      user.normal_image = "http://graph.facebook.com/#{auth.uid}/picture?type=normal"
      user.large_image = "http://graph.facebook.com/#{auth.uid}/picture?type=large"
      user.facebook_url = auth.extra.raw_info.link
      user.gender = auth.extra.raw_info.gender
      user.community_ids = auth.extra.raw_info.gender.titleize == "Female" ? [Community.find_by(name: "Female").id.to_s] : [Community.find_by(name: "Male").id.to_s]
    end
  end
  
  # Check subscription status
  def subscribed?
    Subscription.where(user_id: id).exists?
  end
  
  # Check for unread messages
  def has_unread?
    Message.any_in(conversation_id: conversations.map(&:id)).ne(read_by: id).present?
  end
  
  # Koala
  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
    block_given? ? yield(@facebook) : @facebook
  rescue Koala::Facebook::APIError => e
    logger.info e.to_s
    nil # or consider a custom null object
  end
  
  # Mutual friends
  def mutual_friends(user)
    unless self.id == user.id
      mutual_friends_count = (user.friend_ids & self.friend_ids).length
      pluralize(mutual_friends_count, "mutual friend") if mutual_friends_count > 0
    end
  end

  # Network friends
  def network_friends(community)
    network_friends_count = (friend_ids & community.users.flat_map(&:uid).uniq).length
    pluralize(network_friends_count, "friend") + " in this network" if network_friends_count > 0
  end
  
  # Validation error on signup
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
  
  # Don't require password on signup or update
  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
=begin   
  def relevant_posts
    map = %Q{ function() { emit(this.body, { body: this.body }); } }
    reduce = %Q{ 
      function(key, values) {
        var result = { body: "string" };
        values.forEach(function(value) {
          result.body += value.body;
        });
        return result;
      }
    }    
    Post.in(communities: self.communities).map_reduce(map, reduce).out("relevance_#{self.id}")
  end
  
 
  # Relevance
  def generate_game_stats
    map = "function () { 
      emit(this.user_id, {'points' : this.points, 'moves' : 1});
    }"

    reduce = "function (key, emits) {
      var total = {'points' : 0, 'moves' : 0};
      for (var i in emits) {
        total.points += emits[i].points;
        total.moves  += emits[i].moves;
      }
      return total;
    }"
    db.collection('moves').map_reduce(map, reduce, {:out => "game_stats_#{self.id}", :query => {:game_id => self.id}})
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate_user!
  def home
    @communities = Community.any_in(id: User.all.flat_map(&:community_ids).uniq.compact, community_type: ["School", "Ethnicity", "Field"]).asc(:name)
  end
  
  def index
    # Randomness
    params[:seed] ||= Random.new_seed
    srand params[:seed].to_i
    
    # Users
    community_users = @community.users.all(community_ids: params[:ids]).shuffle
    # Show particular user first
    community_users.unshift User.find_by(id: params[:id]) if params[:id] && params[:ids].blank?
    # Paginate
    @users = Kaminari.paginate_array(community_users).page(params[:page]).per(15)
    
    # Filters
    @filters = Community.in(id: community_users.flat_map(&:community_ids).uniq - [@community.id]).asc(:name)
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_filters.html.haml
- if params[:ids].present?
	.reset_filters
		%span
			\/&nbsp;
			= link_to "reset", params[:controller] == "users" ? users_path : posts_path
- %W[ standing degree field profession company gender relationship orientation religion ethnicity school city state country ].each do |community_type|
	- communities = @filters.where(community_type: community_type.titleize)
	- if communities.present?
		.filters_title
			%span= community_type.titleize
		%ul
			- communities.each do |community|
				%li{:class => selected?(community) ? "selected" : nil}
					= link_to community.filter_name, params[:controller] == "users" ? users_path(ids: set_params!(community)) : posts_path(ids: set_params!(community)), :class => "filter"

app/views/users/_profile.html.haml
.user_profile{id:"#{user.id}_profile"}
	.user_section
		- if user.standing.present?
			.user_standing= user.standing.name
		- if user.degree.present?
			.user_degree= user.degree.name
		- if user.school.present?
			- user.school.to_a.each do |school|
				.user_school= school.name
		- if user.city.present?
			.user_city= user.city.filter_name
	- if user.field.present?
		.user_section
			- user.field.to_a.each do |field|
				.user_field= field.name
	- if user.company.present? || user.profession.present?
		.user_section
			.user_profession
			- user.profession.to_a.each do |profession|
				.user_profession= profession.name
			- user.company.to_a.each do |company|
				.user_company= user.company.name
	- if user.bio?
		.user_section
			.user_bio= user.bio
	- if current_user.mutual_friends(user) || user.network_friends(@community)
		.user_section
			.user_mutual_friends= current_user.mutual_friends(user)
			.user_network_friends= user.network_friends(@community)
	.user_actions
		- unless user == current_user
			- if conversation_exists?(user)
				= link_to conversations_path(id: conversation_id(user)) do
					%i.icon-envelope-alt
			- else
				= link_to new_message_path(id: user), remote: true do
					%i.icon-envelope-alt		
		- if user.show_facebook_url
			= link_to user.facebook_url, target: "_blank" do
				%i.icon-facebook	
		- if user.twitter_name?
			= link_to "http://twitter.com/#{user.twitter_name}", target: "_blank" do
				%i.icon-twitter
		- if user.blog_url?
			= link_to user.blog_url, target: "_blank" do
				%i.icon-rss

app/views/users/_user.html.haml
.user{id:"#{user.id}"}
	.user_image{id:"#{user.id}_image"}
		= link_to image_tag(user.large_image), user_path(user), remote: true
		.user_name= user.first_name
		%i.icon-chevron-down
		

app/views/users/home.html.haml
.row
	.span12
		#home
			.home_title
				select a network
				%i.icon-caret-down
			.home_communities
				- if user_signed_in?
					.home_communities_title
						%span MY NETWORKS
					%ul					
						- current_user.communities.any_in(community_type: ["School", "Ethnicity", "Field"]).asc(:name).each do |community|
							%div= link_to community.name, root_url(subdomain: community.subdomain)				
				- %W[ School Field Ethnicity ].each do |community_type|
					.home_communities_title
						%span= community_type.pluralize
					%ul
						- @communities.where(community_type: community_type).each do |community|
							%div= link_to community.name, root_url(subdomain: community.subdomain)

app/views/users/index.html.haml
- content_for :javascript do
	= javascript_include_tag 'isotope.min', 'users', 'autosize.min'
	
.row
	.span2
		#filters
			#fb-root
			= facebook_share_once
			= render "users/filters"
	.span10
		#users{ :class => @users.blank? ? 'hidden' : nil }
			= render @users
			.div{style:"clear: both"}
		= paginate @users, :remote => true

app/views/users/index.js.erb
//Layout
var $container = $('#users');
var $users = $('<%= j render @users %>');

$container.isotope('insert', $users);
$container.imagesLoaded( function(){
	$container.isotope('reLayout');
});

//Filters
$('#filters').html('<%= j render :partial => "users/filters", :locals => { :filters => @filters } %>');

//Pagination
<% if @users.current_page == @users.num_pages %>
  $('.pagination').remove();
<% else %>
	//Restore pagination div if removed via filtering
	if ( !$('.pagination').length ) {
		$('.span10').append('<div class="pagination"></div>')
	}
  $('.pagination').replaceWith('<%= j paginate @users %>');
<% end %>

app/views/users/show.js.erb
if ( $('#<%= @user.id %>_profile').length ) { 
	$('#<%= @user.id %>_profile').toggle();
} else {
	$('#<%= @user.id %>').append('<%= j render partial: "users/profile", locals: { user: @user } %>');
}
$('#<%= @user.id %>_image i').toggleClass('icon-chevron-down icon-chevron-up');
$('#users').isotope('reLayout');