config/routes.rb
Athirdplace::Application.routes.draw do 
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations", sessions: "sessions"}
  devise_scope :user do
    match "/users/sign_out" => "sessions#destroy"
  end  
  resources :users, only: [:index, :show]
  resources :communities, only: [:index]
  resources :posts
  resources :links
  resources :events
  match 'posts/new/preview', to: 'posts#preview', as: "preview_post"
  match 'posts/new/show_tags', to: 'posts#show_tags', as: "show_tags"
  resources :comments, only: [:new, :create, :show]
  resources :conversations, only: [:index, :show]
  resources :messages, only: [:new, :create]
  resources :subscriptions, only: [:index, :new, :create]
  match "", to: "users#index", constraints: lambda { |r| r.subdomain.present? && r.subdomain != "www" }
  root to: "users#home"
  

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include Geocoder::Model::Mongoid
  include AutoHtmlFor
  
  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :communities

  attr_accessible :_type, :image, :normal_image, :large_image, :start_time, :end_time, :title, :body, :url, :url_host,
                  :user_id, :community_ids, :gender_ids, :standing_ids, :degree_ids, :field_ids, :school_ids, :city_ids,
                  :state_ids, :country_ids, :profession_ids, :company_ids, :relationship_ids, :orientation_ids, 
                  :religion_ids, :ethnicity_ids
  
  validates :body, :presence => { :message => "is blank" }, :unless => Proc.new { |a| a._type == "Link" }

  after_save :add_geo_from_user_city
  
  def add_geo_from_user_city
    if city_ids.present?
      # Add state or country
      if Community.find_by(id: city_ids.first).parent.present?
        self.communities << Community.find_by(id: city_ids.first).parent
      end
      
      # Add country if state
      if Community.find_by(id: city_ids.first).parent.parent.present?
        self.communities << Community.find_by(id: city_ids.first).parent.parent
      end
      
      # Add coordinates
      if Community.find_by(id: city_ids.first).coordinates.present? 
        self.coordinates = Community.find_by(id: city_ids.first).coordinates
      end
    end
  end
  
  field :title, type: String
  field :body, type: String
  field :url, type: String
  field :url_host, type: String
  field :image, type: String
  field :normal_image, type: String
  field :large_image, type: String
  field :start_time, type: DateTime
  field :end_time, type: DateTime
  field :coordinates, type: Array
  
  index({ coordinates: "2d" }, { min: -200, max: 200 })  
  
  auto_html_for :body do
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end
  
  # Create custom methods
  %W[ gender standing degree field school city state country profession company relationship orientation ethnicity religion ].each do |community_type|
    define_method "#{community_type}" do
      array = self.communities.filtered_by(community_type)
      array.length == 1 ? array.first : array
    end
    define_method "#{community_type}_ids" do
      self.communities.filtered_by(community_type).map(&:id)
    end
    define_method "#{community_type}_ids=" do |val| 
      self.communities.clear if community_type == "city"
      
      if community_type == "school" # Schools hack
        val.split(",").each do |school_id|
          self.communities << Community.find_by(id: school_id) if school_id != "[]" # Schools hack
        end
      
      elsif community_type == "profession" || community_type == "company"# Professions hack
        val.split(",").each do |id|
          if Community.where(id: id).exists?
            self.communities << Community.find_by(id: id) if id.present?
          else
            self.communities << Community.create!(name: id, subdomain: id.to_s.delete(" ").delete("-").parameterize, 
                                display_name: "#{id} Network", display_name: "#{id} Network", nickname: val, community_type: community_type.titleize)
          end
        end
      else  
        if val.class == Array
          val.each do |id|
            self.communities << Community.find_by(id: id) if id.present?
          end
        else
          self.communities << Community.find_by(id: val) if val.present? && val != "[]" # Cities hack
        end
      end
    end
  end

  # Relevance
  def relevance(user)
    (self.communities & user.communities).length
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'open-uri'
  def index
    # Posts
    user_posts = Post.in(community_ids: current_user.community_ids).all(community_ids: params[:ids])
    
    # FIXME: Calculate post relevance on the fly with MongoDB 'aggregate' method
    if params[:relevance]
      @posts = {}
      current_user.community_ids.length.downto(1).each do |i|
        user_posts.each do |post|
          if post.relevance(current_user) == i
            @posts[i].present? ? @posts[i] << post : @posts[i] = post.to_a
          end
        end
      end
    else
      @posts = user_posts.desc(:created_at)
    end
    
    # Filters
    @filters = Community.in(id: user_posts.flat_map(&:community_ids).uniq - [@community.id]).asc(:name)
  end
  
  def new
    @post = Post.new
  end
  def create
    @post = Post.new(params[:post])
    @post.user = current_user
    @post.communities << @community
    
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end
  
  def edit
    @post = Post.find_by(id: params[:id])
    redirect_to posts_path unless @post.user == current_user || current_user == User.find_by(email: "abreu.jamil@gmail.com")
  end
  
  def update  
    @post = Post.find_by(id: params[:id])  
    if @post.update_attributes(params[:post])  
      flash[:notice] = "Successfully updated post."  
    end  
    redirect_to posts_path  
  end  
 
  
  def preview
    url = URI.extract(params[:q]).join
    if url.present? && url.include?("facebook.com/events/")
      event_id = url.split("/events/").last.split("/").first
      response = HTTParty.get("https://graph.facebook.com/#{event_id}/", :query => {:access_token => current_user.oauth_token} )
      unless response.parsed_response["error"].present?
        @url = url
        @name = response.parsed_response["name"]
        @body = response.parsed_response["description"]
        
        @image = "https://graph.facebook.com/#{event_id}/picture"
        @normal_image = "https://graph.facebook.com/#{event_id}/picture?type=normal"
        @large_image = "https://graph.facebook.com/#{event_id}/picture?type=large"
        
        @start_time = DateTime.parse response.parsed_response["start_time"]
        @end_time = DateTime.parse response.parsed_response["end_time"]
      end
    elsif url.present?
      # Only allow facebook event URLs for now
      nil
=begin
      begin
        page = Nokogiri::HTML(open(url))
        @url = url
        @host = URI.parse(url).host.gsub("www.", "")
        @title = page.title.split.join(" ")
        # Description
        input = params[:q].gsub(url, "")
        meta_description = page.css("meta[name='description']").first["content"]
        description = input.blank? && meta_description.present? ? meta_description : input
        @description = description.html_safe
      rescue
        nil
      end
=end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_empty.html.haml
.empty_post
	%i.icon-caret-right
	There are no announcements at the moment

app/views/posts/_post.html.haml
.post
	.post_image= link_to image_tag(post.user.large_image), users_path(id: post.user)
	.post_contents
		.post_title= link_to post.user.name, users_path(id: post.user)
		.post_body= truncate_html(post.body_html, length: 280)
		.post_actions
			= link_to comment_path(post), remote: true do
				= pluralize(post.comments.length, 'comment')
				%i.icon-caret-down
			- if current_user == post.user || current_user == User.find_by(email: "abreu.jamil@gmail.com")
				= link_to " | edit", edit_post_path(post)
		.comments{id:"#{post.id}_comments"}
	.div{style:"clear:both"}

app/views/posts/edit.html.haml
- content_for :javascript do
	= javascript_include_tag 'chosen.min', 'select2.min', 'autosize.min', 'posts-edit'

.row
	.span3.hidden-phone
		&nbsp;
	.span9
		#new_post_holder
			- if @post.errors.full_messages.present?
				#error_explanation
					%ul
						- @post.errors.full_messages.each do |msg|
							%li= msg
			= form_for @post, :html => { :class => "form-horizontal", :style => "background: #FFF" } do |f|
				= f.hidden_field :_type
				= f.hidden_field :image
				= f.hidden_field :normal_image
				= f.hidden_field :large_image
				= f.hidden_field :start_time
				= f.hidden_field :end_time
				= f.hidden_field :url
				.post-activity-indicator
				
				#preview_post{:style => "display: block; padding-top: 2px; "}
					#preview_post_image= image_tag @post._type == "Event" ? @post.large_image : current_user.large_image
					#preview_post_contents
						#preview_post_title= f.text_area :title
						#preview_post_url= f.text_area :url_host
						#preview_post_body= f.text_area :body	
					.div{style:"clear:both"}
				
				.form-divider 
					%span= link_to "Add networks [+]", show_tags_path, remote: true

				#optional_fields
					.control-group
						%label.control-label{:for => "post_city"}
							Location
						.controls
							%input{:type => "hidden", :class => "city-select2", :id => "post_city_ids", :name => "post[city_ids]", :style => "width: 220px"}	

					- %W[ field ].each do |type|
						.control-group.multiple
							%label.control-label{:for => "post_#{type}"}
								= "#{type.titlecase}(s)"
							.controls
								= f.collection_select("#{type}_ids".to_sym, Community.filtered_by(type), :id, :name, {:include_blank => true, :selected => params[:post] ? params[:post]["#{type}_ids".to_sym] : @post.community_ids}, {'data-placeholder' => "Select #{type.titlecase}(s) of Experience", :class => 'chzn-select', :id => "post_#{type}", :multiple => true})

					.control-group
						%label.control-label{:for => "post_profession"}
							Profession
						.controls
							%input{:type => "hidden", :class => "profession-select2", :id => "post_profession_ids", :name => "post[profession_ids]", :style => "width: 220px"}	

					.control-group
						%label.control-label{:for => "post_school"}
							School(s)
						.controls
							%input{:type => "hidden", :class => "school-select2", :id => "post_school_ids", :name => "post[school_ids]", :style => "width: 220px"}
							
					- %W[ gender standing degree ].each do |type|
						.control-group
							%label.control-label{:for => "post_#{type}"}
								= type.titlecase
							.controls
								= f.collection_select("#{type}_ids".to_sym, Community.filtered_by(type).ne(name: "High School"), :id, :name, {:include_blank => true, :selected => params[:post] ? params[:post]["#{type}_ids".to_sym] : @post.community_ids}, {'data-placeholder' => "Select #{type.titlecase}", :class => 'chzn-select', :id => "post_#{type}"})


					- %W[ relationship orientation religion ].each do |type|
						.control-group
							%label.control-label{:for => "post_#{type}"}
								= type == 'relationship' ? "Status" : type.titlecase
							.controls
								= f.collection_select("#{type}_ids".to_sym, Community.filtered_by(type), :id, :name, {:include_blank => true, :selected => params[:post] ? params[:post]["#{type}_ids".to_sym] : @post.community_ids}, {'data-placeholder' => "Select #{type == 'relationship' ? "Relationship Status" : type.titlecase}", :class => 'chzn-select', :id => "post_#{type}"})

					- %W[ ethnicity ].each do |type|
						.control-group.multiple
							%label.control-label{:for => "post_#{type}"}
								= type.titlecase
							.controls
								= f.collection_select("#{type}_ids".to_sym, Community.filtered_by(type), :id, :name, {:include_blank => true, :selected => params[:post] ? params[:post]["#{type}_ids".to_sym] : @post.community_ids}, {'data-placeholder' => "Select #{type.titlecase}(s)", :class => 'chzn-select', :id => "post_#{type}", :multiple => true})
	
				
				= f.submit "Update Post", :class => "btn btn-primary", :id => "submit-button"
				
:javascript
	$.ajax({
		url: "/communities.json?post_id=#{@post.id}&post_school=true",
		dataType: 'jsonp',
		success: function(response) {
			if (response.length) {
				$('.school-select2').select2('data', response);
			}
		}
	});
	$.ajax({
		url: "/communities.json?post_id=#{@post.id}&post_city=true",
		dataType: 'jsonp',
		success: function(response) {
			if (response) { //# Note no length
				$('.city-select2').select2('data', response);
			}
		}
	});
	$.ajax({
		url: "/communities.json?post_id=#{@post.id}&post_profession=true",
		dataType: 'jsonp',
		success: function(response) {
			if (response.length) {
				$('.profession-select2').select2('data', response);
			}
		}
	});		

app/views/posts/index.html.haml
- content_for :javascript do
	= javascript_include_tag 'posts', 'autosize.min'
	
.row
	.span2
		#filters
			= render "users/filters"
			&nbsp;
	.span10
		#posts
			#posts-actions
				= link_to new_post_path, :id => "new_post_button" do
					%i.icon-plus
					&nbsp;New Event				
			#posts-inner
				- if @posts.present?
					- if params[:relevant]
						- current_user.community_ids.length.downto(1) do |i|
							= render @posts[i] if @posts[i].present?
					- else
						= render @posts
				- else
					= render partial: "posts/empty"

app/views/posts/index.js.erb
//Layout

<% current_user.community_ids.length.downto(1) do |i| %>
$('#posts-inner').html('<%= j render @posts %>');
<% end %>
					- 
						= render @posts[i] if @posts[i].present?
//Filters
$('#filters').html('<%= j render :partial => "users/filters", :locals => { :filters => @filters } %>');

app/views/posts/new.html.haml
- content_for :javascript do
	= javascript_include_tag 'activity-indicator.min', 'chosen.min', 'select2.min', 'autosize.min', 'posts-new'

.row
	.span3.hidden-phone
		&nbsp;
	.span9
		#new_post_holder
			- if @post.errors.full_messages.present?
				#error_explanation
					%ul
						- @post.errors.full_messages.each do |msg|
							%li= msg
			= form_for @post, :html => { :class => "form-horizontal" } do |f|
				= text_area_tag "body", nil, {:id => "post_input", :size => "40x20", :placeholder => "Paste your Facebook event URL (http://...)" }
				= f.hidden_field :_type
				= f.hidden_field :image
				= f.hidden_field :normal_image
				= f.hidden_field :large_image
				= f.hidden_field :start_time
				= f.hidden_field :end_time
				= f.hidden_field :url
				.post-activity-indicator
				
				#preview_post
					#preview_post_image= image_tag current_user.large_image
					#preview_post_contents
						#preview_post_title= f.text_area :title
						#preview_post_url= f.text_area :url_host
						#preview_post_body= f.text_area :body	
					.div{style:"clear:both"}

				.form-divider 
					%span= link_to "Add more networks [+]", show_tags_path, remote: true

				#optional_fields
					.control-group
						%label.control-label{:for => "post_city"}
							Location
						.controls
							%input{:type => "hidden", :class => "city-select2", :id => "post_city_ids", :name => "post[city_ids]", :style => "width: 220px"}	

					- %W[ field ].each do |type|
						.control-group.multiple
							%label.control-label{:for => "post_#{type}"}
								= "#{type.titlecase}(s)"
							.controls
								= f.collection_select("#{type}_ids".to_sym, Community.filtered_by(type), :id, :name, {:include_blank => true, :selected => params[:post] ? params[:post]["#{type}_ids".to_sym] : (@community ? @community.id : nil)}, {'data-placeholder' => "Select #{type.titlecase}(s) of Experience", :class => 'chzn-select', :id => "post_#{type}", :multiple => true})

					.control-group
						%label.control-label{:for => "post_profession"}
							Profession
						.controls
							%input{:type => "hidden", :class => "profession-select2", :id => "post_profession_ids", :name => "post[profession_ids]", :style => "width: 220px"}	

					.control-group
						%label.control-label{:for => "post_school"}
							School(s)
						.controls
							%input{:type => "hidden", :class => "school-select2", :id => "post_school_ids", :name => "post[school_ids]", :style => "width: 220px"}
							
					- %W[ gender standing degree ].each do |type|
						.control-group
							%label.control-label{:for => "post_#{type}"}
								= type.titlecase
							.controls
								= f.collection_select("#{type}_ids".to_sym, Community.filtered_by(type).ne(name: "High School"), :id, :name, {:include_blank => true, :selected => params[:post] ? params[:post]["#{type}_ids".to_sym] : nil}, {'data-placeholder' => "Select #{type.titlecase}", :class => 'chzn-select', :id => "post_#{type}"})


					- %W[ relationship orientation religion ].each do |type|
						.control-group
							%label.control-label{:for => "post_#{type}"}
								= type == 'relationship' ? "Status" : type.titlecase
							.controls
								= f.collection_select("#{type}_ids".to_sym, Community.filtered_by(type), :id, :name, {:include_blank => true, :selected => params[:post] ? params[:post]["#{type}_ids".to_sym] : (@community ? @community.id : nil)}, {'data-placeholder' => "Select #{type == 'relationship' ? "Relationship Status" : type.titlecase}", :class => 'chzn-select', :id => "post_#{type}"})

					- %W[ ethnicity ].each do |type|
						.control-group.multiple
							%label.control-label{:for => "post_#{type}"}
								= type.titlecase
							.controls
								= f.collection_select("#{type}_ids".to_sym, Community.filtered_by(type), :id, :name, {:include_blank => true, :selected => params[:post] ? params[:post]["#{type}_ids".to_sym] : (@community ? @community.id : nil)}, {'data-placeholder' => "Select #{type.titlecase}(s)", :class => 'chzn-select', :id => "post_#{type}", :multiple => true})
	
								
				= f.submit "Submit Post", :class => "btn btn-primary", :id => "submit-button"

app/views/posts/preview.js.erb
<% if @name %>
	$('.post-activity-indicator').activity(false);
	$('#preview_post').show();
	$('#post__type').val("Event");
	$('#preview_post_url').hide();
	$('#post_url').val('<%= j @url %>');
	$('#post_image').val('<%= j @image.html_safe %>');
	$('#post_normal_image').val('<%= j @normal_image.html_safe %>');
	$('#post_large_image').val('<%= j @large_image.html_safe %>');
	$('#post_start_time').val('<%= @start_time %>');
	$('#post_end_time').val('<%= @end_time %>');
	$('#preview_post_image').html('<%= j image_tag @large_image %>');
	$('#post_title').val('<%= j @name.html_safe %>').trigger('autosize');
	$('#post_body').val('<%= j @body.html_safe %>').trigger('autosize');
<% end %>
/*
<%# elsif @title %>
	$('#post__type').val("Link");
	$('#preview_post_url').show();
	$('#post_url').val('<%= j @url %>');
	$('#post_url_host').val('<%= j @host %>').trigger('autosize');
	$('#post_title').val('<%= j @title %>').trigger('autosize');
	$('#post_body').val('<%= j @description %>').trigger('autosize');	
<%# else %>
	$('#preview_post_url').hide();
	$('#post_title').val('<%= j current_user.name %>').trigger('autosize');
	$('#post_body').val('<%= j params[:q] %>').trigger('autosize');
<%# end %>
*/

app/views/posts/show_tags.js.erb
$('#optional_fields').toggle();