config/routes.rb
Athirdplace::Application.routes.draw do 
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations", sessions: "sessions"}
  devise_scope :user do
    match "/users/sign_out" => "sessions#destroy"
  end  
  resources :users, only: [:index, :show]
  resources :communities, only: [:index]
  resources :posts
  resources :links
  resources :events
  match 'posts/new/preview', to: 'posts#preview', as: "preview_post"
  match 'posts/new/show_tags', to: 'posts#show_tags', as: "show_tags"
  resources :comments, only: [:new, :create, :show]
  resources :conversations, only: [:index, :show]
  resources :messages, only: [:new, :create]
  resources :subscriptions, only: [:index, :new, :create]
  match "", to: "users#index", constraints: lambda { |r| r.subdomain.present? && r.subdomain != "www" }
  root to: "users#home"
  

end

app/views/layouts/_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-7365777-6']);
  _gaq.push(['_setDomainName', 'athirdplace.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/_flash_notice.html.haml
- if notice.present? || alert.present?
	%p.alert.alert-info
		= notice || alert

app/views/layouts/_footer.html.haml
%footer
	- mail_content = capture do
		%i.icon-envelope
		contact
	= mail_to "jamil@athirdplace.com", mail_content, encode: "hex", target: "_blank"

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top.navbar-inverse
	.navbar-inner
		.container
			= link_to root_url(subdomain: false), :class => "brand" do
				3

			%ul.nav
				%li.community_name.hidden-phone= link_to community_name, root_path
				%li.community_name.visible-phone= link_to mobile_name, root_path
			
			%ul.nav.pull-right
				- if @community
					- unless users_page
						%li.divider-vertical
					%li{ :class => users_page ? 'active' : nil }
						= link_to root_url do
							%i.icon-user		
					/- unless users_page || posts_page
					/%li.divider-vertical
					/%li{ :class => posts_page ? 'active' : nil }
					/= link_to posts_path do
					/%i.icon-reorder
					- unless posts_page || conversations_page
						%li.divider-vertical
				- if user_signed_in?
					%li{ :class => conversations_page ? 'active' : nil }
						= link_to conversations_path do
							%i.icon-envelope-alt{ :class => current_user.has_unread? ? 'has_unread' : nil }
					- unless conversations_page
						%li.divider-vertical
					%li.dropdown{ :class => edit_page || subscriptions_page ? 'active' : nil }
						= link_to "#", :class => "dropdown-toggle", "data-toggle" => "dropdown" do
							%i.icon-caret-down
						%ul.dropdown-menu{"role" => "menu", "aria-labelledby" => "dropdownMenu"}
							%li
								= link_to edit_user_registration_path, "tabindex" => "-1"  do
									%i.icon-tasks
									Profile
							%li
								= link_to user_signed_in? && current_user.subscribed? ? subscriptions_path : new_subscription_path, "tabindex" => "-1"  do
									%i.icon-heart
									Support							
							%li.divider
							%li
								= link_to destroy_user_session_path, method: :delete do
									%i.icon-signin
									Logout

app/views/layouts/_login.html.haml
#login
	.container
		.well
			%p.muted= tagline
			= link_to "#{request.protocol + request.domain}/users/auth/facebook", id: "sign_in" do
				%i.icon-facebook-sign
				Sign In with Facebook

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%script{:type => "text/javascript", :src => "http://use.typekit.com/tzo8lux.js"}
		:javascript
			try{Typekit.load();}catch(e){}
		%meta{:charset => "utf-8"}/
		%meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}/
		%title= community_name
		%meta{:name => "description", :content => "#{tagline}"}/
		%meta{:name => "author", :content => "Jamil Abreu"}
		%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}/
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "https://js.stripe.com/v1/"
		= javascript_include_tag "application"
		= javascript_include_tag "login", "facebook", "activity-indicator.min" unless user_signed_in? || home_page
		= yield :javascript
		= csrf_meta_tags
		= tag :meta, name: "stripe-key", content: STRIPE_PUBLIC_KEY
	%body
		/[if lt IE 7]
			%p.chromeframe
				<a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.
		
		= render "layouts/header"
		= render "layouts/login" unless user_signed_in? || home_page || registration_page
				
		.container
			- unless user_signed_in? || home_page || registration_page
				#opaque
			= render "layouts/flash_notice" unless edit_page
			= yield
			.modal.hide{id: "myModal"}
			= render "layouts/footer"
			
		= render "layouts/analytics" if Rails.env.production?
		= debug(params) if Rails.env.development?